title: Vulnerability Research
description: Vulnerability Research
author: Aaron Imperial
github: https://github.com/SkyBulk/exploit-development
about: Vulnerability research guy who's constantly learning new ways to break software.
disqus_shortname: vulnerability
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/blackleitus"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/aron-imperial-213413130/"
    - icon: fa-github
      link: "https://github.com/SkyBulk"

share:
  twitter_username: blackleitus

urls:
    - text: About Me
      url: /about/
    - text: Syllabus
      url: /syllabus/
    - text: tricks
      url: /tricks/

url: "https://github.com/SkyBulk/skybulk.github.io/"
baseurl: "/skybulk"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
